server:
  port: 0

spring:
  application:
    name: ${CAMEL_RABBIT2WEB_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    virtual-host: ${RABBITMQ_VHOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  config:
    import: configserver:http://localhost:8888

# turn on auto declare so the exchange, queues are automatic created if not already present in rabbitmq broker
camel:
  component:
    spring-rabbitmq:
      auto-declare: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

userflow:
  target-service-name: ${CAMEL_WEB2DB_NAME}

