server:
  port: 0

spring:
  application:
    name: ${BARE_DB2WEB_NAME}
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  jpa:
#    open-in-view: off
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

userflow:
  target-service-name: ${BARE_WEB2RABBIT_NAME}
