BARE_DB2WEB_NAME: bare-db2web
BARE_WEB2RABBIT_NAME: bare-web2rabbit
CAMEL_RABBIT2WEB_NAME: camel-rabbit2web
CAMEL_WEB2DB_NAME: camel-web2db

DB_URL: ENTER_YOUR_VALUE
DB_USERNAME: ENTER_YOUR_VALUE
DB_PASSWORD: ENTER_YOUR_VALUE

RABBITMQ_HOST: ENTER_YOUR_VALUE
RABBITMQ_PORT: ENTER_YOUR_VALUE
RABBITMQ_VHOST: ENTER_YOUR_VALUE
RABBITMQ_USERNAME: ENTER_YOUR_VALUE
RABBITMQ_PASSWORD: ENTER_YOUR_VALUE