server:
  port: 0

spring:
  application:
    name: ${BARE_WEB2RABBIT_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    virtual-host: ${RABBITMQ_VHOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: ${RABBITMQ_EXCHANGE}
      routing-key: ${RABBITMQ_ROUTING_KEY}
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

#By default, the path for cxf is: /services. Overriding the default path
cxf:
  path: /cxf
